# Generated by Django 5.2.16 on 2026-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(help_text='One-line summary shown on the projects grid.', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Full write-up. Markdown supported.')),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated, e.g. Python, Django, AWS Lambda, PostgreSQL', max_length=300)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show prominently on the home page.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
