# Generated by Django 5.2.16 on 2026-08-01 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, help_text='One-line summary for the list page.', max_length=300)),
                ('notes', models.TextField(blank=True, help_text='What you learned today. Markdown supported.')),
                ('topic', models.CharField(blank=True, help_text='e.g. AWS, Django, Web Scraping, SQL', max_length=120)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done')], default='open', max_length=20)),
                ('github_issue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('github_issue_url', models.URLField(blank=True)),
                ('branch_name', models.CharField(blank=True, editable=False, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
