# Generated by Django 5.2.16 on 2026-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(help_text='e.g. Data Engineer', max_length=200)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('employment_type', models.CharField(blank=True, help_text='e.g. Full-time, Contract, Internship', max_length=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if this is your current role.', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Responsibilities & impact. Markdown supported.')),
                ('company_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='experience/logos/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
