# Generated by Django 5.2.16 on 2026-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(help_text='e.g. Master of Science', max_length=200)),
                ('field_of_study', models.CharField(blank=True, help_text='e.g. Computer Science', max_length=200)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if in progress.', null=True)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Coursework, thesis, honors, GPA, etc.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='education/logos/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
